Add retry logic to forms-flow-webapi (#2218)

diff --git a/.github/workflows/forms-flow-api-cd.yml b/.github/workflows/forms-flow-api-cd.yml
--- a/.github/workflows/forms-flow-api-cd.yml
+++ b/.github/workflows/forms-flow-api-cd.yml
@@ -79,16 +79,17 @@ jobs:
           sudo mv oc /usr/local/bin/
       - name: Log in to OpenShift
         run: |
-          for i in {1..3}; do
+          for i in {1..9}; do
             if oc login --token=${OPENSHIFT_TOKEN} --server=${OPENSHIFT_SERVER_URL}; then
               echo "Login successful"
-              break
+              exit 0
             fi
-            if [ $i -lt 3 ]; then
-              echo "Login attempt $i failed, retrying in 10 seconds..."
-              sleep 10
+            if [ $i -lt 9 ]; then
+              echo "Login attempt $i failed, retrying in 30 seconds..."
+              sleep 30
             fi
           done
+          exit 1
 
       - name: Checkout repository
         uses: actions/checkout@v3
@@ -175,16 +176,17 @@ jobs:
 
       - name: Log in to OpenShift
         run: |
-          for i in {1..3}; do
+          for i in {1..9}; do
             if oc login --token=${OPENSHIFT_TOKEN} --server=${OPENSHIFT_SERVER_URL}; then
               echo "Login successful"
-              break
+              exit 0
             fi
-            if [ $i -lt 3 ]; then
-              echo "Login attempt $i failed, retrying in 10 seconds..."
-              sleep 10
+            if [ $i -lt 9 ]; then
+              echo "Login attempt $i failed, retrying in 30 seconds..."
+              sleep 30
             fi
           done
+          exit 1
 
       - name: apply deployment
         working-directory: ./deployment/openshift
